### PR TITLE
Strengthen tests

### PR DESCRIPTION
**Pull request by ebebbington**
**Description**

Purpose is to strengthen the tests to ensure as much code and cases are covered (essentially code coverage without the code coverage).

**Current Work Done**

* Ensure create app tests work on Windows

* Expanded upon existing unit tests and created new ones to ensure we cover all bases

### CODE REVIEW

**Comment by ebebbington** [comment]
As of now (disregarding any commits that are made after this comment), i believe we have covered all cases, whether the tests are written or they are commented out due to questions. Though, i'm **sure** there's some things that have been missed, whether it's me not seeing them or not having code coverage.

It's mainly been adding new test files or expanding upon existing tests and I have only touched the unit tests.

There's a fair few TODO's though that I hoping someone can give feedback on 👍

**Comment by Guergeiro** [comment]
What are all those squares in the output?

**Comment by ebebbington** [comment]
> What are all those squares in the output?

Squares?

**Comment by Guergeiro** [comment]
> > What are all those squares in the output?
> 
> Squares?

On Windows tests.

**Comment by crookse** [comment]
I'm done working on this PR. I'll be working in Rhum to debug the CI output stuff.

**Comment by ebebbington** [comment]
@crookse Nice one, and cheers for addressing some of my comments (code comments) 👍

**Pull request merged**
