### PR TITLE
chore: Automate tweets and reddit on release

### PR DESCRIPTION
**Pull request by ebebbington**
**Description**

* should hopefully send a reddit post and tweet on release

### CODE REVIEW

**Comment by ebebbington** [comment]
if it works when drash releases, we can add it to all repos

**Comment by ebebbington** [comment]
Added twitter too, ready for review

**Review by crookse — DISMISSED** [review]
LGTM

**Comment by ebebbington** [comment]
actually woops... the indentation will make it fail D: hold on

**Review by crookse — APPROVED** [review]
still lgtm

**Pull request merged**
