### PR TITLE
chore: Fix http create app tests for forks

### PR DESCRIPTION
**Pull request by ebebbington**

### CODE REVIEW

**Comment by ebebbington** [comment]
This is actually ready for review

**Comment by ebebbington** [comment]
all deletions were because that code was unused

**Comment by MVEMCJSUNPE** [comment]
How about for branches on the main repo? githubOwner is the environment variable 'GITHUB_ACTOR' and drashUrl is 'https://raw.githubusercontent.com/' + githhubOwner + '/deno-drash/' + latestBranch. So the tests would be running on the repository of the person who initiated the workflow instead of drashland.

**Comment by ebebbington** [comment]
> How about for branches on the main repo? githubOwner is the environment variable 'GITHUB_ACTOR' and drashUrl is 'https://raw.githubusercontent.com/' + githhubOwner + '/deno-drash/' + latestBranch. So the tests would be running on the repository of the person who initiated the workflow instead of drashland.

thats the idea, because my testing-ci-from-fork- branch doesn't exist in drashland/deno-drash, neither does your branch, so we need to target your repo

**Comment by MVEMCJSUNPE** [comment]
Nvm I think I made a mistake.

**Comment by ebebbington** [comment]
It is all quite confusing to be honest, i don't know where i am half the time :P

**Comment by ebebbington** [comment]
fyi the tests pass, but it looks like it failed cause the project card thing

**Review by crookse — APPROVED** [review]
LGTM

**Pull request merged**
