### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by drashbot**
This was auto-generated by GitHub Actions.

### CODE REVIEW

**Comment by ebebbington** [comment]
Test deps needed to be updated too, and I have added a section into `DEV.md` to include notes around upgrading deno

**Comment by ebebbington** [comment]
Unfortunately dmm won’t update the test deps because it’ll only update a file named “deps.ts” which I think the test deps file is named “test_deps.ts” - think dmm could add support for this but we can discuss it @crookse @Guergeiro

**Comment by Guergeiro** [comment]
That's why I changed from test_deps.ts to deps.ts.

**Comment by ebebbington** [comment]
Ah, it removed the commits from this PR as well...I don't remember who originally worked on this (hard to tell from the above) but I'll try get it sorted before tomorrows bump (unless @Guergeiro gets to it first i'm not fussed, just want to get it out of the way :P )

**Comment by Guergeiro** [comment]
It's fine. I still think we should make dmm pass a flag that allows the user to choose the name of his `deps.ts` file. We might use the convention, but someone might not. Something like `dmm update --file=myWeirdNameDepsFile.ts`

**Comment by ebebbington** [comment]
> It's fine. I still think we should make dmm pass a flag that allows the user to choose the name of his `deps.ts` file. We might use the convention, but someone might not. Something like `dmm update --file=myWeirdNameDepsFile.ts` Of course this should be cross commands, that is, we can use on check and info.

FYI for PR documentation purposes as I mentioned this in the discord, i created the issue here: https://github.com/drashland/dmm/issues/36

**Pull request merged**
