### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by drashbot**
This was auto-generated by GitHub Actions.

### CODE REVIEW

**Comment by ebebbington** [comment]
Fixed half of the compilation errors, waiting on rhum v1.x to be updated with the fix (fix merged -->. rhum v1.1.1 release --> master merged into v1.x)

**Comment by Guergeiro** [comment]
We need to fix this before the bot runs again (or we will lose @crookse commits) , what's missing?

**Comment by crookse** [comment]
Rhum is broken. The type alias of `Rhum.asserts` is problematic.

**Comment by crookse** [comment]
See: https://github.com/drashland/rhum/pull/45

**Comment by ebebbington** [comment]
This PR relies on that rhum issue being merged, before this PR can be merged,essentially we need to wait until rhum v1.1.1 is released then i'll update the rhum dep and everything should work

**Pull request merged**
