### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by drashbot**
This was auto-generated by GitHub Actions.

### CODE REVIEW

**Comment by ebebbington** [comment]
@crookse @Guergeiro i'm proposing we use a script to automate any other manual tasks we need to do - thoughts?

**Review by Guergeiro — DISMISSED** [review]
I agree with it. I think the bot removed the script though.

**Comment by ebebbington** [comment]
Yeah it did lol, got it all local anyways so will just push it up again

@crookse what do you think about using a script for the repos, to update any other manual work when bumping? eg update deno version in workflows, std version refs in dmm's README

**Comment by crookse** [comment]
@ebebbington sounds good to me

**Comment by ebebbington** [comment]
ok good for a final review

**Review by Guergeiro — APPROVED** [review]
This seems good (I'm on phone), but essentially we still need to manually run the script right?

**Comment by ebebbington** [comment]
It's ran by the bumper CI, so the ci will do it's usual (run dmm update), then run that script

Should note that if it runs and there isn't a newer version released, nothing happens (ie no errors, no code change)

**Pull request merged**
